In [1]:
#reload(sys)
#sys.setdefaultencoding("utf-8")

# 
#   __________
# / ___  ___ \
# / / @ \/ @ \ \
# \ \___/\___/ /\
# \____\/____/||
#   /     /\\\\\//
#  |     |\\\\\\
#  \      \\\\\\
#  \______/\\\\
# _||_||_
# -- --
#Y si ...

In [2]:
#importacion de librerías
import pandas as pd
import sys
import numpy as np

In [3]:
#Cargando datos numericos de la matriz:


#Parametros fijos
archivo = "2016_MIP_12x12.xlsx"
year = 2016

#Vector Hojas, pendiente.

hojas = ["1" , "5" , "7" ,  "9" , "11" ,"13", "15" , "17", "19" , "21"]

hoja = "1"

#numero a saltar de lineas

skip = 8


excel = pd.read_excel("mips/" + archivo ,sheetname=hoja, skiprows=skip)

C:\Users\Bruno\Anaconda3\lib\site-packages\pandas\util\_decorators.py:188: FutureWarning: The `sheetname` keyword is deprecated, use `sheet_name` instead
  return func(*args, **kwargs)

In [4]:
#excel = excel.rename(columns= {'1': 'Producto'}
#Renombrando la primera columna
#excel.rename( columns={'Unnamed: 1':'Producto'}, inplace=True )

excel = excel.rename( columns={'Unnamed: 1':'Producto',
                              'Unnamed: 17':'Consumo_hogares',
                               'Unnamed: 19':'Consumo_IPSFL',
                               'Unnamed: 21':'Consumo_Gob',
                               'Unnamed: 23':'FBKF',
                               'Unnamed: 25':'Var_Existencias',
                               'Unnamed: 27':'Exportaciones',
                              'Unnamed: 29': 'Produccion_PB'})

#Eliminando Total

excel = excel[excel.Producto!="Total"]

In [5]:
#Vector de Producción (X)

X = excel[['Produccion_PB']]

#Eliminado nulos

X = X.dropna()

#Reetiando INdex

X = X.reset_index(drop=True)

In [6]:
#Cargando Coeficientes de de la Matriz Inversa de Lentief

#Cargando datos numericos de la matriz:


#Parametros fijos
archivo = "2016_MIP_12x12.xlsx"
year = 2016

#Vector Hojas, pendiente.

hojas = ["1" , "5" , "7" ,  "9" , "11" ,"13", "15" , "17", "19" , "21"]

hoja = "3"

#numero a saltar de lineas

skip = 6


leontief = pd.read_excel("mips/" + archivo ,sheetname=hoja, skiprows=skip)

In [7]:
#Eliminar todas las filas que sean nan (filas vacías del excel)

leontief = leontief.dropna(how="all")

#Eliminar la primera columna

leontief = leontief.drop(leontief.columns[0], axis=1)
leontief = leontief.drop(leontief.columns[0], axis=1)

#Eliminando la ultima fila con totales de los coeficientes:

leontief.drop(leontief.tail(1).index,inplace=True) # drop last n rows

#Resetiando Index

leontief = leontief.reset_index(drop=True)

In [8]:

y = excel[['Consumo_hogares' , 'Consumo_IPSFL' , 'Consumo_Gob',
     'FBKF' , 'Var_Existencias' , 'Exportaciones' 
     ]]


y = y.dropna()

#Reetiando INdex

y = y.reset_index(drop=True)

#C = Consumo de Hogares
#CIPS = Consumo IPSFL
#G = Consumo gobierno
#I = FBKB
#S = Var Existencias
#EX = Exportaciones

C_p = y[['Consumo_hogares']]
CIPS_p = y[['Consumo_IPSFL']]
G_p = y[['Consumo_Gob']]
I_p = y[['FBKF']]
S_p = y[['Var_Existencias']]
EX_p = y[['Exportaciones']]

In [9]:
#Consumo Total

y2 = y.copy()
y2['Y'] = y2.sum(axis=1)

y2 = y2[['Y']]

#Se resetea el indice, ya que las columnas de la matriz deben llamarse igual que el vector
y2.index = y2.index + 1

In [10]:
# Validacion que la multiplicacion de la inversa de Leontief sea la produccion original:

Xval = leontief.dot(y2)
Z = Xval['Y'] - X['Produccion_PB']
Z

0    -2.885645e-08
1     8.327333e-09
2    -1.586886e-08
3     1.480475e-08
4    -1.455192e-11
5    -1.455192e-09
6    -2.379238e-09
7    -2.199158e-09
8    -3.055902e-10
9     1.329681e-08
10   -2.401066e-10
11   -1.182343e-10
dtype: float64

In [11]:
excel.head(10)

,Unnamed: 0,Producto,1,2,3,4,5,6,7,8,...,Unnamed: 20,Consumo_Gob,Unnamed: 22,FBKF,Unnamed: 24,Var_Existencias,Unnamed: 26,Exportaciones,Unnamed: 28,Produccion_PB
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,1,1941.048885,1.183452,6784.008338,39.265585,5.724630,291.826039,4.299185,3.421194,...,NaN,41.036993,NaN,311.756670,NaN,57.177591,NaN,2469.213715,NaN,13985.638000
3,NaN,2,117.562006,1473.892187,1328.197959,22.349906,106.580794,55.464398,36.587871,24.873678,...,NaN,4.175459,NaN,388.939237,NaN,10.944738,NaN,21128.688882,NaN,24815.837983
4,NaN,3,2148.566560,1237.844275,6366.885208,556.754395,4486.884495,2564.894787,1287.527978,193.080396,...,NaN,65.947855,NaN,1940.992306,NaN,-347.284509,NaN,14618.648760,NaN,51505.562337
5,NaN,4,119.427893,1812.005951,1632.623020,3883.113995,123.502717,593.320907,307.072786,66.468279,...,NaN,61.050755,NaN,71.431677,NaN,0.293898,NaN,98.856110,NaN,12675.040550
6,NaN,5,29.116871,16.757590,55.160557,100.706638,3180.753856,315.147021,171.260448,19.105914,...,NaN,0.217117,NaN,18404.131700,NaN,0.000000,NaN,4.705775,NaN,25224.499081
7,NaN,6,602.162254,760.150936,2048.440435,275.539666,1282.580093,2942.475144,1830.169784,171.856659,...,NaN,479.755211,NaN,2743.797474,NaN,5.565622,NaN,2345.524737,NaN,38664.684731
8,NaN,7,474.528612,989.566357,2904.665125,301.426037,458.184033,3511.515938,4308.918363,566.755242,...,NaN,17.875035,NaN,1547.574866,NaN,0.385909,NaN,2505.407027,NaN,29715.627135
9,NaN,8,395.184269,176.686507,860.131262,250.502164,680.242229,1211.720746,573.868346,1421.642689,...,NaN,83.437764,NaN,33.384699,NaN,0.000000,NaN,346.663512,NaN,13124.072358

# 2.- Obteniendo VA total en una columna para calcular coeficiente de VA

In [12]:
VA = excel[excel.Producto=="Valor agregado "]

In [13]:
#Eliminando Columnas con NA
VA = VA.dropna(axis='columns')
#Eliminando total
del VA['Total']

VA = VA.transpose()



#Eliminando la primera fila

VA = VA[1:]

VA = VA.rename(columns= {22: 'PIB'})

VA = VA.reset_index(drop=True)

In [14]:
# Obteniendo Coeficiente de VA para poder multiplicar con la produccion resultante del Shock:

VA['Coef'] = VA['PIB'] / X['Produccion_PB']

# Generando un shock en la demanda

In [15]:
#Parametros fijos
archivo = "2016_MIP_12x12.xlsx"
year = 2016

#Vector Hojas, pendiente.

hojas = ["1" , "5" , "7" ,  "9" , "11" ,"13", "15" , "17", "19" , "21"]

hoja = "aux_nombres"

skip = 0



aux_nombres = pd.read_excel("mips/" + archivo ,sheetname=hoja, skiprows=skip)

aux_nombres = aux_nombres.rename(index={12: 'Total'})



#Matriz de resultados finales:

columns = ['Actividad', 'Produccion_PB', 'PB_Sim' , 'Dif_pp','fila','columna','shock','year']
resultado_final = pd.DataFrame(columns=columns) #empty dataframe

In [16]:
#shock

#shocks = [0.8,0.9,1.1,1.2]

shocks = np.arange(-1,2,1)



h = 0
z = 0

for shock in shocks:
    for j in range(0,7):

        for i in range(1, 12):
            
            
            #pasando el shock a un float, ya que al dividir este entero generaba
            #valores 0 al transformarse en decimal
            
            shock = float(shock)

            y_sim = y.copy()

            #Resetiando indice para que coincida con actividad y sea de facil lectura
            y_sim.index = y_sim.index + 1

            y_sim

            # Porcentaje del shock
            #i = 1
            #j = 5
            
            #Se creo en el indice j un valor adicional 
            #para calcular el total de una caida en el consumo
            #total, por lo tanto si se llega al ultimo elemento
            #en este caso 6 solo se debe realizar un cambio en el 
            #vector agregado de produccion total
            
            if j<6:

                
                y_sim.ix[i][j]
                y_sim.ix[i][j] = y_sim.ix[i][j] * (1 + ( (shock)/ 100 ))

                y_sim.ix[i][j]
                

            else:
                y_sim.ix[i] = y_sim.ix[i] * (1 + ( (shock)/ 100 ))
                
                

            #Calculando consumo total

            y_sim['PB_Sim'] = y_sim.sum(axis=1)

            y_sim = y_sim[['PB_Sim']]

            #Se resetea el indice, ya que las columnas de la matriz deben llamarse igual que el vector
            #y2.index = y2.index + 1



            #Calculando nueva producción resultante:
            X_sim = leontief.dot(y_sim)



            resultado = pd.concat([X, X_sim], axis=1)


            #Total fila


            #juntando con los nombres:
            resultado.loc['Total'] = resultado.sum()
            #Diferencia porcentual:
            resultado['Dif_pp'] = (resultado['PB_Sim'] / resultado['Produccion_PB']) * 100 - 100   

            resultado = pd.merge(aux_nombres, resultado, left_index=True, right_index=True)



            ### Guardando simulacion

            #fila
            resultado['fila'] = i
            resultado['columna'] = j
            resultado['shock'] = shock
            resultado['year'] = year

            resultado_final = pd.concat([resultado_final,resultado])

            h = h +1
            
            z = z + 1
            
            if z == 100 : 
                z = 0
                print ("iteracion " + str(h))

C:\Users\Bruno\Anaconda3\lib\site-packages\ipykernel_launcher.py:43: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
C:\Users\Bruno\Anaconda3\lib\site-packages\ipykernel_launcher.py:44: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
C:\Users\Bruno\Anaconda3\lib\site-packages\ipykernel_launcher.py:46: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
C:\Users\Bruno\Anaconda3\lib\site-packages\ipykernel_launcher.py:50: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated

iteracion 100
iteracion 200

In [17]:
#Agreando etiquetas para identificar origen del shock
archivo2 = "C:/Proyectos/estadisticas/leontief/aux_leontief.xlsx"

filas = pd.read_excel(archivo2 ,sheetname="aux_filas" ,encoding = 'utf-8')

columnas = pd.read_excel(archivo2 ,sheetname="aux_columnas" , encoding = 'utf-8')

orden = pd.read_excel(archivo2 ,sheetname="aux_orden" , encoding = 'utf-8')

In [18]:
#Agregando actividades
resultado_final2 = pd.merge(resultado_final, filas, how='left', on=None, left_on="fila", right_on="Filas")
#Agregando componente consumo
resultado_final2 = pd.merge(resultado_final2,columnas, how='left', on = None, left_on="columna", right_on="Columnas")
#Agregando auxiliar para ordenar datos segun actividad
resultado_final2 = pd.merge(resultado_final2,orden, how='left', on = None, left_on="Actividad", right_on="Actividades")

In [19]:
resultado_final2.loc[resultado_final2['Actividad']=="Total"].head(5)

,Actividad,Produccion_PB,PB_Sim,Dif_pp,fila,columna,shock,year,Filas,Actividades_x,Columnas,Componente_Consumo,Actividades_y,Orden
12,Total,291262.987541,291228.572435,-0.011816,1,0,-1.0,2016,1,Agropecuario-silvícola y Pesca,0,Consumo_hogares,NaN,NaN
25,Total,291262.987541,291262.611283,-0.000129,2,0,-1.0,2016,2,Minería,0,Consumo_hogares,NaN,NaN
38,Total,291262.987541,290996.479259,-0.091501,3,0,-1.0,2016,3,Industria manufacturera,0,Consumo_hogares,NaN,NaN
51,Total,291262.987541,291212.332817,-0.017391,4,0,-1.0,2016,4,"Electricidad, gas, agua y gestión de desechos",0,Consumo_hogares,NaN,NaN
64,Total,291262.987541,291262.705691,-0.000097,5,0,-1.0,2016,5,Construcción,0,Consumo_hogares,NaN,NaN

In [20]:
#>>> df.drop(columns=['B', 'C'])


resultado_final3 = resultado_final2.drop(['fila','columna','Filas','Columnas'], axis=1)
resultado_final3.index.name = "index"
resultado_final3.to_csv('simulacion_final.csv' , encoding="UTF-8" , sep='|')